[package]
name = "gcookie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3"
dirs = "4.0"
rust-crypto = "0.2.36"
rusqlite = { version = "0.28.0", features = ["bundled"] }
serde_json = "1.0"
base64 = "0.13.0"
url = "2.2.2"

[target.'cfg(windows)'.dependencies]
aes-gcm = "0.9.4"

[target.'cfg(windows)'.dependencies.windows]
version = "0.38.0"
features = [
    "Win32_System_Memory",
    "Win32_Foundation",
    "Win32_Security_Cryptography",
]
